### PR TITLE
Add iteration count to sent worker; Fix log levels

### LINKED ISSUE #136: Change log level for re-send logs
`Ambiguity detected` logs should be considered as warnings.
`nonce too low` logs should be considered as warnings until a certain threshold (specified in `.env`) is reached.

### PR DESCRIPTION
**Pull request by LyzeOfKiel**
Changes:
* Add iteration count to `sentTxWorker`.
* Reduce log level of `Ambiguity detected` errors to warn.
* Reduce log level of `nonce too low` errors to warn (for `sentTxWorker` only).
* Add `SENT_TX_ERROR_THRESHOLD` env. If re-send iteration count is more that this threshold, then corresponding error will be logged.
Closes #136

### CODE REVIEW

File: zp-relayer/config.ts [hunk 1]
```diff
@@ -38,6 +38,7 @@ const config = {
   rpcUrls: (process.env.RPC_URL as string).split(' ').filter(url => url.length > 0),
   relayerTxRedundancy: process.env.RELAYER_TX_REDUNDANCY === 'true',
   sentTxDelay: parseInt(process.env.SENT_TX_DELAY || '30000'),
+  sentTxLogErrorThreshold: parseInt(process.env.SENT_TX_ERROR_THRESHOLD || '3'),
```
Comment (k1rill-fedoseev) [inline zp-relayer/config.ts:41]: Missing entry in `CONFIGURATION.md`

**Review by r0wdy1 — APPROVED** [review]
