### PR TITLE
Fix/updated hash

### LINKED ISSUE #81: Return updated hash {R22.11}
`/job/:id` endpoint should return updated transaction hash in case it has changed after re-sending. Now, it returns only the first transaction hash got after initial sending.

### LINKED ISSUE #89: Log txhash for resent transactions
Currently if the relayer resends a transaction with new data (e.g. re-estimated gas price), the transaction hash does not appear in the logs so it is difficult to track correspondence between a transaction on the block explorer and data handled by the relayer.

Here is examples of transactions:
- https://polygonscan.com/tx/0x7a64e8a0b0e47784004b13d5a2898e2f42795da94705af40fd02554d9a9f729e
- https://polygonscan.com/tx/0xe8801256a1890733d8b5d6a43b7a64fa7ad30e847b3c1657fc981c1254401f4f

The [log file](https://github.com/zkBob/zeropool-relayer/files/9923675/zkbob-relayer-20221102.log) from the relayer for the corresponding time range.

### LINKED ISSUE #95: Validate permit deposit signature more precisely {22.11}
Current relayer implementation check user account balance incorrect: it restores the user address from the signature. Instead, it should get address from the memo. If address from the memo differs restored from signature address - it's mean that signature was made incorrect

### PR DESCRIPTION
**Pull request by LyzeOfKiel**
Updates:
* Fix minor logging issues found after deploying on staging:
    1. Validation errors now are considered as warnings
    2. Changed `debug` level to `info` in some places
    3. Added log for re-sent transaction hash (Closes #89)
* Enhance signature validation (Closes #95). Compare recovered address with owner field from memo. If these addresses mismatch, the we don't need to check token balance and can throw a corresponding error.
* Update job status model with following statuses: `waiting`, `failed`, `sent`, `reverted`, `completed`. Description:
    `waiting` - job is waiting in queue or being processed by `poolTxWorker`
    `failed` - job failed validation step before it was submitted to contract
    `sent` - job is being processed by `sentTxWorker`
    `reverted` - job got a confirmed revert
    `completed` - job completed successfully
    Expected `/job/:id` response type for each status:
    * `waiting`: 
        ```ts
        {
            createdOn: number
            failedReason: null
            finishedOn: null
            state: "waiting"
            txHash: null
        }
        ```
    * `failed`:
        ```ts
        {
            createdOn: number
            failedReason: string
            finishedOn: number
            state: "failed"
            txHash: null
        }
        ```
    * `sendt`:
        ```ts
        {
            createdOn: number
            failedReason: null
            finishedOn: null
            state: "sent"
            txHash: string
        }
        ```
    * `reverted`:
        ```ts
        {
            createdOn: number
            failedReason: null
            finishedOn: number
            state: "reverted"
            txHash: string
        }
        ```
    * `completed`:
        ```ts
        {
            createdOn: number
            failedReason: null
            finishedOn: number
            state: "completed"
            txHash: string
        }
        ```
* Added `JobIdsMapping`. It is required to track statuses of re-submitted to `poolTxQueue` failed jobs. After job is re-submitted back to the queue, a new record is stored in redis linking original pool job id to the new one.
* Update transaction hash in optimistic state after transaction re-send (Closes #81)

### CODE REVIEW

File: zp-relayer/endpoints.ts [hunk 1]
```diff
@@ -108,22 +109,82 @@ async function getTransactionsV2(req: Request, res: Response, next: NextFunction
...
 async function getJob(req: Request, res: Response) {
+  enum JobStatus {
+    WAITING = 'waiting',
+    FAILED = 'failed',
+    SENDED = 'sended',
+    REVERTED = 'reverted',
+    COMPLETED = 'completed',
+  }
+
+  interface GetJobResponse {
```
Comment (k1rill-fedoseev) [inline zp-relayer/endpoints.ts:120]: Let's also add the actual job id, which was resolved from the mapping

File: zp-relayer/workers/sentTxWorker.ts [hunk 2]
```diff
@@ -140,18 +143,26 @@ export async function createSentTxWorker<T extends EstimationType>(gasPrice: Gas
...
         const reschedulePromises = []
+        const newPoolJobIdMapping: Record<string, string> = {}
         const waitingJobs = await sentTxQueue.getJobs(['delayed', 'waiting'])
         for (let wj of waitingJobs) {
           // One of the jobs can be undefined, so we need to check it
           // https://github.com/taskforcesh/bullmq/blob/master/src/commands/addJob-8.lua#L142-L143
           if (!wj?.id) continue
           waitingJobIds.push(wj.id)
-          reschedulePromises.push(poolTxQueue.add(txHash, [wj.data.txPayload]).then(j => j.id as string))
+          const reschedulePromise = poolTxQueue.add(txHash, [wj.data.txPayload]).then(j => {
```
Comment (k1rill-fedoseev) [inline zp-relayer/workers/sentTxWorker.ts:153]: What will happen if one of Redis requests will fail, but others won't?

I guess it would be better if we use batch/atomic transactions to make group actions in places like this. I assume there are many similar places in the code, so let's do it under a separate issue/PR later on.

File: zp-relayer/endpoints.ts [hunk 3]
```diff
@@ -108,22 +109,82 @@ async function getTransactionsV2(req: Request, res: Response, next: NextFunction
...
+      if (!sentJob) throw new Error('Sent job not found')
+
+      const sentJobState = await sentJob.getState()
+      if (sentJobState === 'waiting' || sentJobState === 'active' || sentJobState === 'delayed') {
+        // Transaction is in re-send loop
+        const txHash = sentJob.data.prevAttempts.at(-1)?.[0]
+        result.state = JobStatus.SENDED
+        result.txHash = txHash || null
+      } else if (sentJobState === 'completed') {
+        const [txState, txHash] = sentJob.returnvalue
```
Comment (k1rill-fedoseev) [inline zp-relayer/endpoints.ts:159]: We shouldn't see 'SKIPPED' state here, because such jobs are added to the jobs remapping hset, right?

**Review by k1rill-fedoseev — CHANGES_REQUESTED** [review]

File: zp-relayer/endpoints.ts [hunk 4]
```diff
@@ -108,22 +109,82 @@ async function getTransactionsV2(req: Request, res: Response, next: NextFunction
...
-    res.json({
-      state,
-      txHash,
-      failedReason,
-      createdOn,
-      finishedOn,
-    })
+
+  async function getPoolJobState(requestedJobId: string): Promise<GetJobResponse | null> {
+    const jobId = await pool.state.jobIdsMapping.get(requestedJobId)
```
[the remark this answers is not in the document]
Comment (LyzeOfKiel) [reply zp-relayer/endpoints.ts:131]: Yes, `jobIdsMapping.get` is recursive

File: zp-relayer/endpoints.ts (hunk 3 above)
Comment (LyzeOfKiel) [reply zp-relayer/endpoints.ts:159]: Yes, if a job was re-scheduled, it will be in mapping hset, and we will get actual mapped job here
https://github.com/zkBob/zeropool-relayer/blob/369eeb62c4d9dfff262a0c24b78223eb55e7dd73/zp-relayer/endpoints.ts#L131

File: zp-relayer/workers/sentTxWorker.ts (hunk 2 above)
Comment (LyzeOfKiel) [reply zp-relayer/workers/sentTxWorker.ts:153]: In this case we firstly add new jobs to the queue, then update `jobIdsMapping`. So, job re-scheduling do not depend on id mapping update. Do you suggest to make these two actions atomic? Also, how would we handle such redis requests errors?

Comment (k1rill-fedoseev) [reply zp-relayer/workers/sentTxWorker.ts:153]: It's a good practice to make all db updates during worker iteration within atomic transaction. Case when we re-schedule the job, but don't update the id mapping is not good.

Any error within the worker iteration, which cannot be handled, should rollback the current transaction, as if nothing has ever happened.

Comment (LyzeOfKiel) [reply zp-relayer/workers/sentTxWorker.ts:153]: I will check if it is possible to easily integrate atomic transactions with `bullmq`.

Comment (k1rill-fedoseev) [reply zp-relayer/workers/sentTxWorker.ts:153]: Thanks, it is not a big problem anyway, no need to address it in this PR

**Review by k1rill-fedoseev — APPROVED** [review]
lgtm

**Review by EvgenKor — COMMENTED** [review]
The code looks good. It's need to test it on the staging
