### PR TITLE
Fix tx resend

### LINKED ISSUE #35: Add permit deadline check when resending a transaction

### LINKED ISSUE #49: Handle different error strings from different clients/implementations
Example here: https://github.com/omni/tokenbridge/blob/ff9f3fb7d6b4b8b484b4ef92427ce03411265714/oracle/src/utils/utils.js#L147-L187

### LINKED ISSUE #51: Actualise gas price/nonce when transaction is re-sent
Although the relayer already has a mechanism to re-send transactions consider to improve it by identifying whether a transaction is stuck due to low gas price or it is disappeared due to re-used nonce. Depending on the reason the transaction must be resent with updated gas price or nonce.

### LINKED ISSUE #52: Gas price oracles features propagation form tokenbridge
Although the gas price oracle has been improved as part of the work on #32 consider to go through the corresponding implementation in the tokenbridge oracle to check that all features from it were propagated in the relayer code.

Here is the list of features:
- both upper and lower limits on gas prices (legacy gas price / priority fee / max fee per gas)
- configurable multiplicative factors on values returned by gas price oracles

### LINKED ISSUE #74: Fix transaction resending in sentTxWorker {R7.11}
Now, in case transaction is not mined, after gas price is updated in transaction config, transaction is not resent. After some time, such transactions can be lost in the mempool.
Need to add resend functionality in the `sentTxWorker.ts` after updating gas price config.

https://github.com/zkBob/zeropool-relayer/blob/3900473042ede50540cad8b9a4c4af7aae85c37f/zp-relayer/workers/sentTxWorker.ts#L125-L130

### LINKED ISSUE #77: Add limit for maxFeePerGas
Add configurable limit for `maxFeePerGas` to prevent relayer from sending high-cost transactions

### PR DESCRIPTION
**Pull request by LyzeOfKiel**
Closes #35 
Added assertion for permit deadline when resending a transaction.
https://github.com/zkBob/zeropool-relayer/blob/68e93a906abc45469a7be9f541f04d6c5bb3f728/zp-relayer/workers/sentTxWorker.ts#L137-L140

Closes #49 
Added handling of some client errors when resending a transaction.
https://github.com/zkBob/zeropool-relayer/blob/68e93a906abc45469a7be9f541f04d6c5bb3f728/zp-relayer/workers/sentTxWorker.ts#L177
https://github.com/zkBob/zeropool-relayer/blob/68e93a906abc45469a7be9f541f04d6c5bb3f728/zp-relayer/workers/sentTxWorker.ts#L180

Closes #51 
Gas price is updated if corresponding error was thrown during transaction re-send. Related to #49 

Closes #52 
See #77 

Closes #74 
Implemented proper transaction re-send mechanism. Re-send errors related to gasPrice/nonce are handled. Other errors are considered as unrecoverable, and in this case optimistic state rollback is performed.
https://github.com/zkBob/zeropool-relayer/blob/68e93a906abc45469a7be9f541f04d6c5bb3f728/zp-relayer/workers/sentTxWorker.ts#L183-L187

Closes #77 
Added `MAX_FEE_PER_GAS_LIMIT` env variable for limiting max value of `maxFeePerGas`.
Gas parameters are calculated as follows:
`new_maxFeePerGas = min(MAX_FEE_PER_GAS_LIMIT, old_maxFeePerGas)`
`new_maxPriorityFeePerGas = max(0, old_maxPriorityFeePerGas - (old_maxFeePerGas - MAX_FEE_PER_GAS_LIMIT))` 
This behaviour is described in tests.

### CODE REVIEW

File: zp-relayer/validateTx.ts [hunk 1]
```diff
@@ -233,7 +231,13 @@ export async function validateTx({ txType, rawMemo, txProof, depositSignature }:
     userAddress = await getRecoveredAddress(txType, nullifier, txData, requiredTokenAmount, depositSignature)
     await checkAssertion(() => checkDepositEnoughBalance(userAddress, requiredTokenAmount))
   }
+  if (txType === TxType.PERMITTABLE_DEPOSIT) {
+    const deadline = (txData as PermittableDepositTxData).deadline
+    await checkAssertion(() => checkDeadline(deadline))
```
Comment (k1rill-fedoseev) [inline zp-relayer/validateTx.ts:236]: I think we should also configure some buffer window for checking the deadline. e.g. we should reject transactions, whose deadline will expire in 5 seconds, since it won't be mined in such short time in any case.

I would suggest the following:
* During the initial transaction sending, we should reject transaction with deadline in less than 10 minutes
* During transaction resend, we should reject transaction with deadline in less than 10 seconds

File: zp-relayer/services/gas-price/GasPrice.ts [hunk 2]
```diff
@@ -26,6 +29,43 @@ const polygonGasPriceKeyMapping: Record<GasPriceKey, PolygonGSV2GasPriceKey> = {
...
+
+export function EIP1559GasPriceWithinLimit(fees: EIP1559GasPrice, maxFeeLimit: BN | null): EIP1559GasPrice {
+  if (!maxFeeLimit) return fees
+
+  const diff = toBN(fees.maxFeePerGas).sub(maxFeeLimit)
+  if (diff.isNeg()) {
+    return fees
+  } else {
+    const maxFeePerGas = maxFeeLimit.toString(10)
+    const maxPriorityFeePerGas = BN.max(toBN(fees.maxPriorityFeePerGas).sub(diff), toBN(0)).toString(10)
```
[the remark this answers is not in the document]
Comment (LyzeOfKiel) [reply zp-relayer/services/gas-price/GasPrice.ts:61]: Agree

File: zp-relayer/validateTx.ts (hunk 1 above)
Comment (LyzeOfKiel) [reply zp-relayer/validateTx.ts:236]: Agree. Maybe it is better to create a special env (e.g. `PERMIT_DEADLINE_RESEND_WINDOW`) for this deadline window for resend case? And calculate initial sending window as `PERMIT_DEADLINE_RESEND_WINDOW + 10 min`.

Comment (k1rill-fedoseev) [reply zp-relayer/validateTx.ts:236]: Current threshold in library is set to 5 minutes, so let's stick to that value for now, for the initial tx sending check - https://github.com/zkBob/zkbob-client-js/pull/34

**Comment by LyzeOfKiel** [comment]
New changes:
* Added two variables for threshold configuration:
`PERMIT_DEADLINE_THRESHOLD_INITIAL` (default: 300)
`PERMIT_DEADLINE_THRESHOLD_RESEND` (default: 10)
* Added test `checkDeadline` method with thresholds
* Refactoring

File: zp-relayer/workers/sentTxWorker.ts [hunk 3]
```diff
@@ -99,55 +124,81 @@ export async function createSentTxWorker<T extends EstimationType>(gasPrice: Gas
...
-        const root2 = pool.optimisticState.getMerkleRoot()
-        logger.info(`Assert roots are equal: ${root1}, ${root2}, ${root1 === root2}`)
+        await clearOptimisticState()
+        return [SentTxState.REVERT, txHash] as SentTxResult
       }
     } else {
+      // Resend with updated gas price
+      if (txType === TxType.PERMITTABLE_DEPOSIT) {
+        const deadline = (txData as PermittableDepositTxData).deadline
+        await checkAssertion(() => checkDeadline(deadline, config.permitDeadlineThresholdResend))
```
Comment (k1rill-fedoseev) [inline zp-relayer/workers/sentTxWorker.ts:139]: Can you clarify, what will happen with the this particular job if the deadline will be expired at this point? What will happen with the jobs that are positioned later in the optimistic state?

Comment (LyzeOfKiel) [reply zp-relayer/workers/sentTxWorker.ts:139]: This part with deadline check should be moved inside try-catch block below (just before transaction submission), so that this error will be caught and state rollback is performed. Will fix now.

**Comment by LyzeOfKiel** [comment]
Changes:
* Moved deadline validation in try-catch block. If validation will fail, all succeeding optimistic transactions will be erased and optimistic state will be cleared.
* Changed some `BN` types to `string`, as they potentially can cause errors in queue-worker communication.

**Review by k1rill-fedoseev — APPROVED** [review]
lgtm

I hope this cases will be well-covered by the e2e auto tests in the future...
