### PR TITLE
Fix events block range

### LINKED ISSUE #125: Check block range for requests for events
Relayer error:
```
error: Returned error: eth_getLogs block range too large, range: 3501, max: 3500 {"timestamp":"2022-12-30T18:01:52.171Z"}
```
Configuration:
```
EVENTS_PROCESSING_BATCH_SIZE=3500
```

### PR DESCRIPTION
**Pull request by LyzeOfKiel**
Changes:
* Fix block range for `getEvents`. Example range requests for `BATCH_SIZE=10000`: `(0..9999)`, `(10000..19999)`, `(20000..29999)`. Previously it was: `(0..10000)`, `(10000..20000)`, `(20000..30000)`.
Closes #125

### CODE REVIEW

File: zp-relayer/pool.ts [hunk 1]
```diff
@@ -154,12 +154,12 @@ class Pool {
     }
 
     const lastBlockNumber = await this.getLastBlockToProcess()
-    let finishBlock = fromBlock
-    for (let startBlock = fromBlock; finishBlock <= lastBlockNumber; startBlock = finishBlock) {
-      finishBlock += config.eventsProcessingBatchSize
+    let toBlock = startBlock
+    for (let fromBlock = startBlock; toBlock <= lastBlockNumber + 1; startBlock = toBlock) {
+      toBlock += config.eventsProcessingBatchSize
```
Comment (k1rill-fedoseev) [inline zp-relayer/pool.ts:159]: Why we don't take minimum of `toBlock` and `lastBlockNumber + 1` here?

Comment (LyzeOfKiel) [reply zp-relayer/pool.ts:159]: Actually, we can. But, why is this important?

Comment (k1rill-fedoseev) [reply zp-relayer/pool.ts:159]: This means we can process same event at the end of the interval multiple times, should be extra careful that nothing breaks (i.e. all state modifications) on such repeated processing

Comment (LyzeOfKiel) [reply zp-relayer/pool.ts:159]: >This means we can process same event at the end of the interval multiple times

Why?

Anyway, all state updates in `syncState` loop are idempotent, so nothing would break if same event would be processed twice.
The original issue, was that range event queries included `BATCH_SIZE+1` elements and RPC rejected it.
